dns:
  from_ipv4:
    execution:
      mode: parallel
      concurrency: 20
      timeout_ms: 5000

    tests:
      # TEST 0
      - id: google_safesearch
        type: dns_query

        input:
          qname: www.google.com
          qtype: A
          resolver: default

        assertions:
          all:
            - op: contains
              value: forcesafesearch.google.com

        critical: false

      # TEST 1
      - id: test_domain_flashstart
        type: dns_query

        input:
          qname: test_domain.flashstart.com
          qtype: A
          resolver: default

        assertions:
          all:
            - op: equals
              value: 185.236.106.107

        critical: false

      # TEST 2
      - id: check_blacklist
        type: dns_query

        input:
          qname: www.xxx.com
          qtype: A
          resolver: default

        assertions:
          all:
            - op: not_contains
              value: stop.fsflt.net

        critical: false

      # TEST 3
      - id: check_blocklist_facebook
        type: dns_query

        input:
          qname: www.facebook.com
          qtype: A
          resolver: default

        assertions:
          all:
            - op: contains
              value: stop.fsflt.net

        critical: false

      # TEST 4
      - id: check_filtering
        type: dns_query

        input:
          qname: sex.com
          qtype: A
          resolver: default

        assertions:
          all:
            - op: contains
              value: stop.fsflt.net

        critical: false

      # TEST SAFESEARCH
      - id: check_safesearch_google
        type: dns_query

        input:
          qname: www.google.com
          qtype: A
          resolver: default

        assertions:
          all:
            - op: contains
              value: forcesafesearch.google.com

        critical: false

      # TEST YOUTUBE
      - id: check_safesearch_youtube
        type: dns_query

        input:
          qname: www.youtube.com
          qtype: A
          resolver: default

        assertions:
          all:
            - op: contains
              value: restrictmoderate.youtube.com

        critical: false

      # TEST DUCKDUCKGO
      - id: check_safesearch_duckduck
        type: dns_query

        input:
          qname: www.duckduckgo.com
          qtype: A
          resolver: default

        assertions:
          all:
            - op: contains
              value: safe.duckduckgo.com

        critical: false

      # TEST DYNDNS
      - id: check_dyndns
        type: dns_query

        input:
          qname: members.dyndns.org
          qtype: A
          resolver: default

        assertions:
          all:
            - op: equals
              value: 185.236.104.104

      # TEST NIC UPDATE IPV4
      - id: nic_update_basic
        type: nic_update
        input:
          hostname: "ddns.flashstart.com"
          username: "${NIC_UPDATE_USERNAME}"
          password: "${NIC_UPDATE_PASSWORD}"
          url: "nic/update?hostname=test_hosting.com&wildcard=NOCHG&mx=NOCHG&backmx=NOCHG"
        assertions:
          all:
            - op: equals
              value: "good"

# ==================================== IPV6 ============================================
  from_ipv6:
    execution:
      mode: parallel
      concurrency: 10
      timeout_ms: 5000

    tests:
      - id: ipv6_google_resolution
        type: dns_query
        input:
          qname: google.com
          qtype: AAAA
          resolver: default
        assertions:
          all:
            - op: contains
              value: ":"
        critical: true

      - id: ipv6_safesearch_check
        type: dns_query
        input:
          qname: www.google.com
          qtype: AAAA
          resolver: default
        assertions:
          all:
            - op: not_contains
              value: "DNS_TIMEOUT"
        critical: false

      # TEST NIC UPDATE IPV6
      - id: nic_update_basic
        type: nic_update
        input:
          hostname: "ddns.flashstart.com"
          username: "${NIC_UPDATE_USERNAME}"
          password: "${NIC_UPDATE_PASSWORD}"
          url: "nic/update?hostname=test_hosting.com&wildcard=NOCHG&mx=NOCHG&backmx=NOCHG"
        assertions:
          all:
            - op: equals
              value: "good"

#nic_update:
#  - id: "nic_update_basic"
#    name: "Verifica risposta nic/update"
#    type: "nic_update"
#    input:
#      hostname: "ddns.flashstart.com"
#      username: "host_testing@flashstart.com"
#      password: "Cloud001$$"
#      url: "nic/update?hostname=test_hosting.com&wildcard=NOCHG&mx=NOCHG&backmx=NOCHG"
#    assertions:
#      all:
#        - op: "equals"
#          value: "good"
